### ISSUE TITLE
Vulnerability: react-scripts > webpack-dev-server > yargs > yargs-parser

### ISSUE THREAD

**Issue by zw627** [zw627/react-router-github-pages#11]
```
react-scripts > webpack-dev-server > yargs > yargs-parser
```

See https://github.com/webpack/webpack-dev-server/issues/2559 for more info.

**Comment by zw627** [comment]
Fixed in `webpack-dev-server` [3.11.0](https://github.com/webpack/webpack-dev-server/releases/tag/v3.11.0).

Waiting for `react-scripts` to upgrade its `webpack-dev-server` dependency.

**Comment by dillu24** [comment]
Has this been solved in `react-scripts` ? The same vulnerability error is still being raised.

**Comment by zw627** [comment]
@dillu24 Apparently not yet.

https://github.com/facebook/create-react-app/releases

**Comment by sonikamah** [comment]
> Has this been solved in `react-scripts` ? The same vulnerability error is still being raised.



> Has this been solved in `react-scripts` ? The same vulnerability error is still being raised.

Is dere any solution to it, as my build is getting failed ?

**Comment by zw627** [comment]
> > Has this been solved in `react-scripts` ? The same vulnerability error is still being raised.
> 
> Is dere any solution to it, as my build is getting failed ?

I am afraid you will have to wait for the maintainers of `create-react-app` to upgrade its `webpack-dev-server` dependency. Meanwhile, you should try to create your own Webpack-React boilerplate, so situations like this can be avoided in the future.

**Comment by sonikamah** [comment]
> Webpack-React boilerplate

Thanks for your reply, then its better I should create webpack react boilerplate.

**Comment by lausellduane** [comment]
I am having the same issue, any updates on this?

**Comment by zw627** [comment]
> I am having the same issue, any updates on this?

It has already been fixed in the master branch as early as [8th May](https://github.com/facebook/create-react-app/pull/8975), but they have not released anything since [20th March](https://github.com/facebook/create-react-app/releases).

See also: [#9033](https://github.com/facebook/create-react-app/issues/9033), [#8529](https://github.com/facebook/create-react-app/issues/8529), [#8970](https://github.com/facebook/create-react-app/issues/8970).
